/* ═══════════════════════════════════════════════════════════════
   FEYNOTES — Course Configuration
   Single source of truth for all courses and lesson metadata.
   Add a course here + its theme in base.css → everything else
   is generated automatically by build.js.
   ═══════════════════════════════════════════════════════════════ */

const SITE = {
  url: 'https://eliacinti.dev',
  title: 'FeyNotes',
  author: 'Elia Cinti',
  description: 'Appunti di Ingegneria Informatica — Tor Vergata',
  cssVersion: 14,
};

const COURSES = {
  fisica: {
    id: 'fisica',
    theme: 'fisica',
    name: 'Fisica 1',
    icon: '⚛️',
    basePath: '/fisica1',
    indexUrl: '/fisica1/',
    professor: 'Prof. Mercuri',
    university: 'Università di Roma Tor Vergata',
    year: 'A.A. 2025/2026',
    lessonLabel: 'Lezione',
    description: 'Guida allo studio con lezioni, formule, animazioni interattive e visualizzazioni Manim per capire la fisica davvero.',
    nav: [
      { label: 'Lezioni', href: '/fisica1/', active: true },
      { label: 'Formulario', href: '#' },
      { label: 'Esercizi', href: '#' },
    ],
    categories: [
      { id: 'cinematica', label: 'cinematica', gridId: 'cinematica-grid' },
      { id: 'dinamica', label: 'dinamica', gridId: 'dinamica-grid' },
      { id: 'termodinamica', label: 'termodinamica', gridId: 'termo-grid' },
    ],
    lessons: [
      { id: 'L01', num: 'Lezione 1', date: '11 Mar 2026', title: 'Introduzione, Metodo Scientifico e Prime Grandezze Cinematiche', abstract: 'Metodo galileiano, grandezze scalari vs vettoriali, posizione, spostamento, velocità media.', category: 'cinematica' },
      { id: 'L02', num: 'Lezione 2', date: '4 Mar 2026', title: 'Vettore Posizione, Coseni Direttori e Velocità', abstract: 'Coseni direttori, versori fondamentali, somma vettoriale, velocità istantanea come derivata.', category: 'cinematica' },
      { id: 'L03', num: 'Lezione 3', date: '5 Mar 2026', title: 'Velocità Istantanea, Accelerazione e Moto Rettilineo', abstract: 'Tangenza della velocità, accelerazione, decomposizione intrinseca, moto rettilineo uniforme.', category: 'cinematica' },
      { id: 'L04', num: 'Lezione 4', date: '9 Mar 2026', title: 'Moto Uniformemente Accelerato e Caduta Libera', abstract: 'Equazioni del moto UA, caduta libera, composizione dei moti, moto del proiettile.', category: 'cinematica' },
      { id: 'L05', num: 'Lezione 5', date: '11 Mar 2026', title: 'Moto Circolare Uniforme e Moto Circolare Uniformemente Accelerato', abstract: 'MCU, MCUA, velocità angolare, accelerazione centripeta, relazione grandezze lineari-angolari.', category: 'cinematica' },
      { id: 'L06', num: 'Lezione 6', date: '12 Mar 2026', title: 'Fondamenti di Cinematica del Moto Circolare', abstract: 'Descrizione angolare del moto, leggi orarie MCU e MCUA, periodo e frequenza, trattazione vettoriale con prodotto vettoriale, esercizi svolti.', category: 'cinematica' },
      { id: 'L07', num: 'Lezione 7', date: '16 Mar 2026', title: 'Introduzione alla Dinamica: Le Leggi di Newton, Quantita di Moto e Impulso', abstract: 'Dalla cinematica alla dinamica. Prima e Seconda Legge di Newton. Massa inerziale. Quantita di moto, teorema dell\'impulso, forze impulsive e forza media.', category: 'dinamica' },
      { id: 'L08', num: 'Lezione 8', date: '18 Mar 2026', title: 'Terzo Principio, Risoluzione Vettoriale delle Forze e Forza Peso', abstract: 'Terzo principio (azione-reazione). Equilibrio statico 2D con scomposizione vettoriale. Corpi a contatto. Forza peso e reazione normale.', category: 'dinamica' },
      { id: 'L09', num: 'Lezione 9', date: '19 Mar 2026', title: 'Esercizi, Vincoli, Reazione Normale e Attrito', abstract: 'Esercizi su MCUA e teorema dell\'impulso (pallina da tennis contro muro). Vincoli e forze vincolari. Reazione normale. Attrito statico e dinamico.', category: 'dinamica' },
      { id: 'L10', num: 'Lezione 10', date: '25 Mar 2026', title: 'Dinamica: Forze di Contatto, Attrito e Reazioni Vincolari', abstract: 'RN ≠ mg: problema dell\'ascensore (5 casi). Piano inclinato con e senza attrito. Esercizio fondamentale: cassa tirata con fune inclinata.', category: 'dinamica' },
      { id: 'L11', num: 'Lezione 11', date: '27 Mar 2026', title: 'La Forza Elastica e il Moto Armonico Semplice', abstract: 'Il modello della molla ideale. Vettore deformazione e Legge di Hooke. Sistema massa-molla in 1D. Derivazione dell\'equazione del moto armonico. Pulsazione, periodo e frequenza.', category: 'dinamica' },
      { id: 'L12', num: 'Lezione 12', date: '1 Apr 2026', title: 'Moto Armonico Semplice: Soluzione, Sistemi di Molle e Attrito Viscoso', abstract: 'Soluzione dell\'equazione del moto armonico. Determinazione di ampiezza e fase iniziale. Molle in parallelo e in serie. Attrito viscoso lineare: velocità limite e soluzione analitica.', category: 'dinamica' },
      { id: 'L13', num: 'Lezione 13', date: '2 Apr 2026', title: 'La Tensione e le Funi Ideali', abstract: 'Definizione di fune ideale e tensione come forza vincolare. Proprietà della tensione costante lungo una fune priva di massa. Applicazioni classiche: masse collegate su piano orizzontale, macchina di Atwood, massa sospesa a due funi. Forza centripeta e attrito statico nell\'automobile in curva.', category: 'dinamica' },
      { id: 'L14', num: 'Lezione 14', date: '8 Apr 2026', title: 'Lavoro, Energia Cinetica e Forze Conservative', abstract: 'Dal prodotto scalare forza-spostamento nasce il concetto di lavoro; il teorema delle forze vive lo collega alla variazione di energia cinetica. Si classificano le forze in conservative e dissipative e si introduce l\'energia potenziale.', category: 'dinamica' },
      { id: 'L15', num: 'Lezione 15', date: '9 Apr 2026', title: 'Lavoro, Energia e Forze Conservative', abstract: 'Applicazione del teorema dell\'energia cinetica a problemi di dinamica, introduzione delle forze conservative e dell\'energia potenziale, principio di conservazione dell\'energia meccanica, effetto delle forze non conservative e definizione di potenza.', category: 'dinamica' },
      { id: 'L16', num: 'Lezione 16', date: '13 Apr 2026', title: 'Esercizi su Lavoro ed Energia, Introduzione al Momento Angolare', abstract: 'Esercizi applicativi sul teorema dell\'energia meccanica (piano inclinato con e senza attrito, guida circolare verticale), seguiti dall\'introduzione al momento angolare, al momento della forza e alla seconda equazione cardinale della dinamica.', category: 'dinamica' },
      { id: 'L17', num: 'Lezione 17', date: '15 Apr 2026', title: 'Momento Angolare e Fenomeni Rotatori', abstract: 'Costruzione del formalismo della dinamica rotazionale: dal momento di un vettore al momento angolare, passando per il teorema del momento angolare (seconda equazione cardinale), il teorema del momento dell\'impulso e il lavoro nelle rotazioni.', category: 'dinamica' },
      { id: 'L19', num: 'Lezione 19', date: '20 Apr 2026', title: 'Moti Relativi e Forze Apparenti', abstract: 'Cinematica e dinamica dei moti relativi: formula di Poisson, composizione di velocità e accelerazioni tra sistemi di riferimento, forze apparenti (trascinamento, centrifuga, Coriolis) nei sistemi non inerziali.', category: 'dinamica' },
      { id: 'L20', num: 'Lezione 20', date: '22 Apr 2026', title: 'Sistemi di Riferimento non Inerziali, Forze Apparenti e Forze Centrali', abstract: 'Analisi della dinamica nei sistemi di riferimento non inerziali con introduzione delle forze apparenti (trascinamento, Coriolis, centrifuga), seguita dalla classificazione delle forze centrali e dalle loro tre proprietà fondamentali: conservazione del momento angolare, velocità areolare costante e natura conservativa.', category: 'dinamica' },
      { id: 'L21', num: 'Lezione 21', date: '23 Apr 2026', title: 'Forze Centrali e Gravitazione Universale', abstract: 'Dimostrazione delle tre proprietà fondamentali delle forze centrali (conservazione del momento angolare, legge delle aree, conservatività), formulazione della legge di gravitazione universale di Newton, distinzione tra massa inerziale e gravitazionale, e derivazione dell\'energia potenziale gravitazionale.', category: 'dinamica' },
      { id: 'L27', num: 'Lezione 22', date: '27 Apr 2026', title: 'Dinamica dei Sistemi di Punti Materiali', abstract: 'Estensione della dinamica dal punto materiale ai sistemi: forze interne ed esterne, centro di massa, Prima e Seconda Equazione Cardinale, conservazione della quantità di moto e del momento angolare, Teorema di König per l\'energia cinetica.', category: 'dinamica' },
      { id: 'L28', num: 'Lezione 23', date: '29 Apr 2026', title: 'Conservazione della Quantità di Moto e Momento Angolare', abstract: 'Applicazioni della conservazione della quantità di moto (uomo su barca, proiettile che esplode), introduzione del momento angolare e della seconda equazione cardinale, conservazione del momento angolare con esempio del sistema rotante, e problema del blocco su cuneo mobile con doppia conservazione.', category: 'dinamica' },
      { id: 'L29', num: 'Lezione 24', date: '30 Apr 2026', title: 'Dinamica dei Sistemi e Sistema di Riferimento del Centro di Massa', abstract: 'Consolidamento delle equazioni cardinali della dinamica dei sistemi, principi di conservazione (quantità di moto, momento angolare, energia meccanica), applicazione completa con esempio molla-blocchi e introduzione del Sistema di Riferimento del Centro di Massa (SRCM).', category: 'dinamica' },
      { id: 'L30', num: 'Lezione 25', date: '04 Mag 2026', title: 'Momento Angolare ed Energia Cinetica nei Sistemi di Riferimento: I Teoremi di König', abstract: 'Derivazione completa dei due Teoremi di König: scomposizione del momento angolare in contributo orbitale e proprio, scomposizione dell\'energia cinetica in contributo del centro di massa e interno. Applicazione alla classificazione degli urti.', category: 'dinamica' },
      { id: 'L31', num: 'Lezione 26', date: '06 Mag 2026', title: 'Dinamica dei sistemi di punti e fenomeni d\'urto', abstract: 'Dalle equazioni cardinali della dinamica dei sistemi alla classificazione completa dei fenomeni d\'urto: conservazione della quantità di moto, urti elastici e anelastici, teoremi di König e applicazioni.', category: 'dinamica' },
      { id: 'L33', num: 'Lezione 27', date: '07 Mag 2026', title: 'Classificazione degli Urti e Coefficiente di Restituzione', abstract: 'Classificazione degli urti in base alla conservazione dell\'energia cinetica: urti elastici, completamente anelastici e anelastici. Introduzione del coefficiente di restituzione e derivazione della relazione tra velocità relative. Applicazioni: palla che rimbalza, pendolo balistico e culla di Newton.', category: 'dinamica' },
      { id: 'L36', num: 'Lezione 28', date: '13 Mag 2026', title: 'Il Corpo Rigido: Definizioni e Proprietà', abstract: 'Definizione di corpo rigido e vincolo di rigidità. Lavoro nullo delle forze interne e conseguenze energetiche. Calcolo del centro di massa per corpi continui con densità volumica, superficiale e lineare. Esempi: sbarra omogenea, semicirconferenza, sbarra non omogenea. Cinematica: pura traslazione, pura rotazione e moto roto-traslatorio.', category: 'dinamica' },
      { id: 'L38', num: 'Lezione 29', date: '14 Mag 2026', title: 'Dinamica del Corpo Rigido: Rotazione attorno a un Asse Fisso', abstract: 'Spostamenti infinitesimi di un corpo rigido come combinazione di traslazione e rotazione. Rotazione attorno a un asse fisso: momento angolare assiale, momento di inerzia e l\'equazione fondamentale della dinamica rotazionale M_z = I_z α. Analogia completa traslazione–rotazione. L\'effetto ballerina come applicazione della conservazione del momento angolare.', category: 'dinamica' },
      { id: 'L39', num: 'Lezione 30', date: '18 Mag 2026', title: 'Dinamica della rotazione: momento di inerzia, energia cinetica e teorema di Huygens-Steiner', abstract: 'Momento di inerzia per corpi discreti e continui, energia cinetica di rotazione, teorema delle forze vive in forma rotazionale, calcolo dei momenti di inerzia notevoli e teorema di Huygens-Steiner per assi paralleli.', category: 'dinamica' },
      { id: 'L40', num: 'Lezione 31', date: '20 Mag 2026', title: 'Moto di puro rotolamento, baricentro e pendolo composto', abstract: 'Cinematica e dinamica del puro rotolamento con le due descrizioni equivalenti (rotazione istantanea e roto-traslazione). Trazione del carro e ruota motrice. Centro delle forze parallele e baricentro. Il pendolo composto. Urti con corpi rigidi e cenni di statica.', category: 'dinamica' },
      { id: 'L41', num: 'Lezione 32', date: '21 Mag 2026', title: 'Introduzione alla Termodinamica e Primo Principio', abstract: 'Passaggio dalla meccanica alla termodinamica: sistemi termodinamici, temperatura, stati di equilibrio, trasformazioni quasi-statiche e reversibili, Principio Zero, esperimento di Joule, energia interna e formulazione del Primo Principio con applicazioni alle trasformazioni speciali.', category: 'termodinamica' },
      { id: 'L46', num: 'Lezione 33', date: '25 Mag 2026', title: 'Il lavoro in termodinamica', abstract: 'Dal primo principio della termodinamica alla riscrittura del lavoro meccanico in variabili termodinamiche: derivazione di δL = p dV, integrale per trasformazioni finite e convenzione dei segni.', category: 'termodinamica' },
      { id: 'L47', num: 'Lezione 34', date: '27 Mag 2026', title: 'Riepilogo di termodinamica: sistemi monofasici, bifasici e diagramma di Clapeyron', abstract: 'Classificazione dei sistemi termodinamici, scambi termici in sistemi monofasici (calore specifico) e bifasici (calore latente), unità di misura, Primo Principio della Termodinamica e diagramma di Clapeyron con esempio guidato di ciclo a tre trasformazioni.', category: 'termodinamica' },
      { id: 'L49', num: 'Lezione 35', date: '28 Mag 2026', title: 'Gas ideali: energia interna, espansione libera di Joule e Relazione di Mayer', abstract: 'Si dimostra che l\'energia interna di un gas ideale dipende solo dalla temperatura tramite l\'esperimento di Joule, si ricava l\'espressione esplicita ΔU = nCᵥΔT valida per qualunque trasformazione, e si deriva la Relazione di Mayer Cₚ − Cᵥ = R. Anticipazione sulle adiabatiche reversibili.', category: 'termodinamica' },
    ],
  },

  // ─── Future courses — uncomment and fill when ready ───
  // ─── Future courses — uncomment and fill when ready ───

  geometria: {
    id: 'geometria',
    theme: 'geometria',
    name: 'Geometria',
    icon: '△',
    basePath: '/geometria',
    indexUrl: '/geometria/',
    professor: 'Trusiani / Di Gennaro',
    university: 'Università di Roma Tor Vergata',
    year: 'A.A. 2025/2026',
    lessonLabel: 'Lezione',
    description: 'Appunti di Geometria per Ingegneria Informatica. Spazi vettoriali, matrici, sistemi lineari, applicazioni lineari, forme quadratiche e geometria analitica.',
    nav: [
      { label: 'Lezioni', href: '/geometria/', active: true },
    ],
    categories: [
      { id: 'spazi-vettoriali', label: 'spazi vettoriali', gridId: 'spazi-grid' },
      { id: 'matrici', label: 'matrici', gridId: 'matrici-grid' },
      { id: 'sistemi-lineari', label: 'sistemi lineari', gridId: 'sistemi-grid' },
      { id: 'applicazioni-lineari', label: 'applicazioni lineari', gridId: 'applicazioni-grid' },
      { id: 'forme-quadratiche', label: 'forme quadratiche', gridId: 'forme-grid' },
      { id: 'geometria-analitica', label: 'geometria analitica', gridId: 'geoanalitica-grid' },
    ],
    lessons: [
      { id: 'L01', num: 'Lezione 1', date: '2 Mar 2026', title: 'Spazi Vettoriali', abstract: 'Definizione rigorosa di spazio vettoriale, gli 8 assiomi fondamentali, le 7 proprietà di calcolo con relative dimostrazioni, e i primi esempi costruttivi.', category: 'spazi-vettoriali' },
      { id: 'L02', num: 'Lezione 2', date: '3 Mar 2026', title: 'Ulteriori Esempi di Spazi Vettoriali', abstract: 'Dai calcoli espliciti in ℝ² alla generalizzazione in ℝⁿ, passando per lo spazio delle matrici M(m,n), lo spazio dei polinomi ℝ[t] e i vettori geometrici: una panoramica completa sugli spazi vettoriali fondamentali.', category: 'spazi-vettoriali' },
      { id: 'L03', num: 'Lezione 3', date: '5 Mar 2026', title: 'Sottospazi Vettoriali e Vettori Geometrici', abstract: 'Dai vettori geometrici alla teoria dei sottospazi vettoriali: definizioni, caratterizzazioni, verifiche complete con esempi in ℝ², ℝ³ e ℝ[t]. Combinazioni lineari e Span.', category: 'spazi-vettoriali' },
      { id: 'L04', num: 'Lezione 4', date: '9 Mar 2026', title: 'Sottospazio Generato, Proprietà dello Span e Spazi Finitamente Generabili', abstract: 'Definizione formale di span (sottospazio generato), esempi di calcolo, le 6 proprietà fondamentali con dimostrazioni, sistemi di generatori, spazi finitamente generabili e il caso critico di ℝ[t].', category: 'spazi-vettoriali' },
      { id: 'L05', num: 'Lezione 5', date: '10 Mar 2026', title: 'Spazi Geometrici Finitamente Generabili e Indipendenza Lineare', abstract: 'Dimostrazione grafica che gli spazi vettoriali geometrici (1D, 2D, 3D) sono finitamente generabili. Metodo algebrico per trovare generatori di sottospazi definiti da equazioni. Definizione rigorosa di indipendenza e dipendenza lineare, con catalogo completo delle proprietà e caratterizzazione fondamentale.', category: 'spazi-vettoriali' },
      { id: 'L06', num: 'Lezione 6', date: '12 Mar 2026', title: 'Proprietà dei Sistemi Liberi e Legati', abstract: 'Proprietà fondamentali dei sistemi di vettori liberi e legati: caratterizzazione tramite dipendenza lineare, vettori sovrabbondanti, unicità delle coordinate, e l\'algoritmo di scarto per estrarre generatori indipendenti.', category: 'spazi-vettoriali' },
      { id: 'L07', num: 'Lezione 7', date: '16 Mar 2026', title: 'Basi, Lemma di Steinitz e Dimensione', abstract: 'Definizione rigorosa di base di uno spazio vettoriale, dimostrazione del Lemma di Steinitz (sostitutivo) per assurdo, e introduzione del concetto di dimensione con le sue proprietà equivalenti.', category: 'spazi-vettoriali' },
      { id: 'L08', num: 'Lezione 8', date: '17 Mar 2026', title: 'Basi, Dimensione e Formula di Grassmann', abstract: 'Definizione di dimensione di uno spazio vettoriale, le 8 proprietà fondamentali di basi e dimensione, intersezione e somma di sottospazi, e dimostrazione completa della Formula di Grassmann.', category: 'spazi-vettoriali' },
      { id: 'L09', num: 'Lezione 9', date: '19 Mar 2026', title: 'Esercizi su Grassmann, Somma Diretta e Inizio Matrici', abstract: 'Applicazione pratica della Formula di Grassmann per calcolare basi e dimensioni di somma e intersezione di sottospazi. Definizione e caratterizzazioni equivalenti della somma diretta. Introduzione al capitolo delle matrici: notazioni, trasposta, traccia e famiglie notevoli.', category: 'spazi-vettoriali' },
      { id: 'L10', num: 'Lezione 10', date: '24 Mar 2026', title: 'Operazioni tra Matrici, Invertibilità e Trasposizione', abstract: 'Prodotto riga per colonna, algebra delle matrici quadrate, matrici invertibili con formula per il caso 2×2, e matrice trasposta con tutte le proprietà.', category: 'matrici' },
      { id: 'L11', num: 'Lezione 11', date: '26 Mar 2026', title: 'Rango, Sottomatrici e Operazioni Elementari', abstract: 'Spazio delle righe e delle colonne di una matrice, Teorema del Rango con dimostrazione completa, sottomatrici e disuguaglianza sul rango, operazioni elementari sulle righe, matrici elementari e loro invertibilità, equivalenza per righe come relazione di equivalenza.', category: 'matrici' },
      { id: 'L12', num: 'Lezione 12', date: '30 Mar 2026', title: 'Matrici Equivalenti per Righe, Matrice a Scala e Algoritmo di Gauss', abstract: 'Equivalenza per righe e conservazione dello spazio delle righe. Definizione di matrice a scala e pivot. L\'algoritmo di Gauss per la riduzione a scala. Calcolo del rango, basi di sottospazi, verifica di appartenenza allo span, complementi in somma diretta e discussione del rango con parametri.', category: 'matrici' },
      { id: 'L13', num: 'Lezione 13', date: '31 Mar 2026', title: 'Rango di Matrici e Introduzione al Determinante', abstract: 'Proprietà fondamentali del rango (effetto del prodotto e dell\'invertibilità), definizione del determinante tramite sviluppo di Laplace, esempi di calcolo su matrici 3×3, e metodo di Gauss per il determinante.', category: 'matrici' },
      { id: 'L14', num: 'Lezione 14', date: '2 Apr 2026', title: 'Proprietà del Determinante, Teorema di Binet e Matrice Inversa', abstract: 'Completiamo le proprietà del determinante, dimostriamo il legame tra rango e determinante, enunciamo il Teorema Fondamentale dell\'Invertibilità, il Teorema di Binet e ricaviamo la formula esplicita per la matrice inversa tramite l\'aggiunta classica.', category: 'matrici' },
      { id: 'L15', num: 'Lezione 15', date: '9 Apr 2026', title: 'Algoritmo di Gauss-Jordan e Calcolo del Rango (Teorema degli Orlati)', abstract: 'Metodo efficiente per il calcolo della matrice inversa tramite l\'algoritmo di Gauss-Jordan. Calcolo del rango di una matrice qualunque tramite i minori e il potente Teorema degli Orlati.', category: 'matrici' },
      { id: 'L16', num: 'Lezione 16', date: '13 Apr 2026', title: 'Teorema degli Orlati e Sistemi Lineari', abstract: 'Dimostrazione completa del teorema degli orlati con esempio dettagliato di calcolo del rango. Introduzione ai sistemi lineari: definizioni, forma matriciale, teorema di Rouché-Capelli e algoritmo di eliminazione di Gauss con sostituzione all\'indietro.', category: 'sistemi-lineari' },
      { id: 'L17', num: 'Lezione 17', date: '14 Apr 2026', title: 'Sistemi Lineari e Determinanti', abstract: 'Teorema di Rouché-Capelli per la compatibilità dei sistemi lineari, discussione di sistemi con parametro e teorema di Cramer per la risoluzione tramite determinanti.', category: 'sistemi-lineari' },
      { id: 'L18', num: 'Lezione 18', date: '16 Apr 2026', title: 'Sistemi Lineari Rettangolari e Rappresentazioni di Sottospazi', abstract: 'Come risolvere sistemi rettangolari con Cramer, l\'algoritmo generale di riduzione, e il passaggio tra rappresentazione cartesiana e parametrica di sottospazi vettoriali.', category: 'sistemi-lineari' },
      { id: 'L19', num: 'Lezione 19', date: '20 Apr 2026', title: 'Rappresentazione Cartesiana e Sistemi Lineari', abstract: 'Dalla rappresentazione parametrica a quella cartesiana di un sottospazio vettoriale: algoritmo costruttivo, calcolo di intersezioni tramite equazioni, sistema omogeneo associato, struttura delle soluzioni come sottospazio affine e proprietà fondamentali dei sottospazi affini.', category: 'sistemi-lineari' },
      { id: 'L20', num: 'Lezione 20', date: '21 Apr 2026', title: 'Coordinate e Matrice del Cambiamento di Base', abstract: 'Definizione formale delle coordinate di un vettore rispetto a una base, matrice del cambiamento di base con le sue proprietà (invertibilità, composizione, identità), e l\'applicazione delle coordinate come isomorfismo lineare tra V e ℝⁿ.', category: 'applicazioni-lineari' },
      { id: 'L21', num: 'Lezione 21', date: '23 Apr 2026', title: 'Applicazione delle Coordinate e Applicazioni Lineari', abstract: 'Dall\'applicazione delle coordinate (biettiva e lineare) che traduce qualsiasi spazio vettoriale in ℝⁿ, alle applicazioni lineari: definizione, proprietà di calcolo, esempi fondamentali e controesempi.', category: 'applicazioni-lineari' },
      { id: 'L22', num: 'Lezione 22', date: '27 Apr 2026', title: 'Matrice Associata a un\'Applicazione Lineare', abstract: 'Come ogni applicazione lineare tra spazi di dimensione finita può essere rappresentata da una matrice, una volta scelte le basi. Costruzione della matrice rappresentativa, proprietà fondamentali (azione sui vettori, composizione, invertibilità) e esempi di calcolo dettagliati.', category: 'applicazioni-lineari' },
      { id: 'L23', num: 'Lezione 23', date: '28 Apr 2026', title: 'Nucleo e Immagine di Applicazioni Lineari', abstract: 'Esempi geometrici di applicazioni lineari nel piano (rotazioni, riflessioni, proiezioni ortogonali), definizione di nucleo e immagine, criteri di iniettività e suriettività, e il fondamentale Teorema della Dimensione (Rank-Nullity).', category: 'applicazioni-lineari' },
      { id: 'L24', num: 'Lezione 24', date: '30 Apr 2026', title: 'Nucleo e Immagine di Applicazioni Lineari', abstract: 'Metodi pratici per calcolare basi di nucleo e immagine di un\'applicazione lineare tramite coordinate e matrici rappresentative. Teorema della dimensione (del rango). Isomorfismi tra spazi vettoriali.', category: 'applicazioni-lineari' },
      { id: 'L25', num: 'Lezione 25', date: '4 Mag 2026', title: 'Proprietà degli Isomorfismi e Diagonalizzabilità', abstract: 'Classificazione degli spazi vettoriali tramite isomorfismi, lo spazio Hom(V,V\') e la sua struttura, formula del cambio di base A\' = P⁻¹AP, matrici simili e introduzione alla diagonalizzabilità con esempi ed esempi di matrici non diagonalizzabili.', category: 'applicazioni-lineari' },
      { id: 'L26', num: 'Lezione 26', date: '05 Mag 2026', title: 'Autovalori, autovettori e polinomio caratteristico', abstract: 'Il problema centrale della diagonalizzazione: quando un endomorfismo ammette una base di autovettori? Definiamo autovalori, autovettori e polinomio caratteristico, e introduciamo le molteplicità algebrica e geometrica come strumenti per rispondere a questa domanda.', category: 'applicazioni-lineari' },
      { id: 'L32', num: 'Lezione 27', date: '07 Mag 2026', title: 'Molteplicità Algebrica e Geometrica e Algoritmo di Diagonalizzazione', abstract: 'Introduzione delle molteplicità algebrica e geometrica di un autovalore, dimostrazione della relazione fondamentale tra le due, e derivazione dell\'algoritmo completo di diagonalizzazione con esempio applicativo.', category: 'applicazioni-lineari' },
      { id: 'L34', num: 'Lezione 28', date: '11 Mag 2026', title: 'Autovettori, Diagonalizzabilità e Forme Bilineari', abstract: 'Dimostrazione del lemma fondamentale sull\'indipendenza lineare di autovettori relativi ad autovalori distinti, esercizio completo di diagonalizzazione su ℝ³, e introduzione alle forme bilineari simmetriche con la matrice di Gram.', category: 'applicazioni-lineari' },
      { id: 'L35', num: 'Lezione 29', date: '12 Mag 2026', title: 'Forme Bilineari Simmetriche e Matrice di Gram', abstract: 'Definizione rigorosa di forma bilineare simmetrica, costruzione della matrice di Gram rispetto a una base, formula di cambiamento di base (congruenza), esempi dettagliati su ℝⁿ e spazi di polinomi.', category: 'forme-quadratiche' },
      { id: 'L37', num: 'Lezione 30', date: '14 Mag 2026', title: 'Congruenza, forme quadratiche e diagonalizzazione', abstract: 'Come cambia la matrice di Gram al variare della base: la relazione di congruenza. Forme quadratiche come modo equivalente di descrivere forme bilineari simmetriche. L\'algoritmo di Gauss-Lagrange per diagonalizzare qualsiasi forma quadratica.', category: 'forme-quadratiche' },
      { id: 'L42', num: 'Lezione 31', date: '18 Mag 2026', title: 'Spazi pseudoeuclidei, Teorema di Sylvester e basi ortonormali', abstract: 'Dimostrazione rigorosa del Teorema di Sylvester (legge di inerzia), che garantisce l\'invarianza di rango, indice e segnatura di una forma bilineare simmetrica reale. Introduzione degli spazi pseudoeuclidei, costruzione delle basi ortonormali e forma canonica per congruenza di una matrice simmetrica.', category: 'forme-quadratiche' },
      { id: 'L43', num: 'Lezione 32', date: '19 Mag 2026', title: 'Forma canonica per congruenza e classificazione degli spazi pseudoeuclidei', abstract: 'Dalla base ortonormale alla forma canonica per congruenza: unicità garantita dal Teorema di Sylvester, criterio di congruenza tra matrici simmetriche, classificazione completa degli spazi pseudoeuclidei (definito positivo, semidefinito, indefinito) e introduzione allo spazio euclideo.', category: 'forme-quadratiche' },
      { id: 'L44', num: 'Lezione 33', date: '21 Mag 2026', title: 'Spazi euclidei: criteri di positività, norma e angolo', abstract: 'Criteri operativi per riconoscere matrici definite positive (minori principali e Jacobi), definizione di spazio euclideo, norma, ortogonalità, parallelismo, disuguaglianza di Cauchy-Schwarz, angolo tra vettori e disuguaglianza triangolare.', category: 'forme-quadratiche' },
      { id: 'L45', num: 'Lezione 34', date: '25 Mag 2026', title: 'Proiezione ortogonale e procedimento di Gram-Schmidt', abstract: 'Introduzione alla proiezione ortogonale di un vettore su un altro vettore in uno spazio euclideo, con il coefficiente di Fourier. Procedimento di ortogonalizzazione di Gram-Schmidt per costruire basi ortonormali. Estensione della proiezione ortogonale a sottospazi di dimensione arbitraria, complemento ortogonale e decomposizione in somma diretta.', category: 'forme-quadratiche' },
      { id: 'L48', num: 'Lezione 35', date: '26 Mag 2026', title: 'Proiezione ortogonale su un sottospazio: proprietà e calcolo', abstract: 'Richiami sugli spazi euclidei e sulla proiezione ortogonale. Dimostrazione delle proprietà fondamentali della decomposizione ortogonale, linearità della proiezione come endomorfismo, spettro e diagonalizzabilità. Esempio completo di calcolo in ℝ⁴: base ortogonale, proiezione del generico vettore e matrice rappresentativa.', category: 'forme-quadratiche' },
    ],
  },
  controlli: {
    id: 'controlli',
    theme: 'controlli',
    name: 'Fondamenti di Controlli',
    icon: '◎',
    basePath: '/controlli',
    indexUrl: '/controlli/',
    professor: '',
    university: 'Università di Roma Tor Vergata',
    year: 'A.A. 2025/2026',
    lessonLabel: 'Guida',
    description: 'Guide risolutive per gli esercizi di Fondamenti di Controlli, organizzate per blocchi tematici.',
    nav: [
      { label: 'Guide', href: '/controlli/', active: true },
    ],
    categories: [
      { id: 'blocco-1', label: 'blocco 1 — equilibrio e linearizzazione', gridId: 'blocco1-grid' },
      { id: 'blocco-2', label: 'blocco 2 — sistemi meccanici', gridId: 'blocco2-grid' },
      { id: 'blocco-4', label: 'blocco 4 — dalla soluzione al sistema', gridId: 'blocco4-grid' },
      { id: 'blocco-5', label: 'blocco 5 — fratti semplici', gridId: 'blocco5-grid' },
      { id: 'blocco-6', label: 'blocco 6 — equazioni differenziali', gridId: 'blocco6-grid' },
      { id: 'blocco-7', label: 'blocco 7 — equazioni alle differenze', gridId: 'blocco7-grid' },
      { id: 'blocco-8', label: 'blocco 8', gridId: 'blocco8-grid' },
      { id: 'blocco-9', label: 'blocco 9', gridId: 'blocco9-grid' },
      { id: 'blocco-10', label: 'blocco 10', gridId: 'blocco10-grid' },
    ],
    lessons: [
      { id: 'L01', num: 'Guida 1', date: '6 Apr 2026', title: 'Equilibrio e Linearizzazione', abstract: 'Come partire da un sistema fisico non lineare, trovare il punto di equilibrio e costruire le matrici numeriche A, B, C, D attraverso la linearizzazione.', category: 'blocco-1' },
      { id: 'L02', num: 'Guida 2', date: '6 Apr 2026', title: 'Modellazione Meccanica: da Lagrange allo Spazio di Stato', abstract: 'Procedura completa per ricavare il modello nello spazio di stato (ẋ = Ax + Bu) a partire da un sistema meccanico, passando per i gradi di libertà, le energie T, U, F, la tabella di Eulero-Lagrange e la scelta delle variabili di stato.', category: 'blocco-2' },
      { id: 'L03', num: 'Guida 3', date: '6 Apr 2026', title: 'Dalla Soluzione al Sistema (Blocco 4)', abstract: 'Dato y(t) con costanti arbitrarie, ricostruire l\'equazione differenziale (o alle differenze) originale del sistema usando l\'operatore Δ. Procedura in 4 step: individuare i poli nascosti, costruire il polinomio caratteristico, calcolare la forzante e scrivere l\'equazione finale.', category: 'blocco-4' },
      { id: 'L04', num: 'Guida 4', date: '6 Apr 2026', title: 'Decomposizione in Fratti Semplici', abstract: 'Come spezzare una frazione', category: 'blocco-5' },
      { id: 'L05', num: 'Guida 5', date: '5 Mag 2026', title: 'Risoluzione delle Equazioni Differenziali', abstract: 'Procedura completa per risolvere $p(\\Delta)\\, y(t) = u(t)$: soluzione omogenea con la tabella dei modi, soluzione particolare (metodo classico, ingresso esponenziale, risonanza), generale non omogenea con calcolo delle costanti $C$, risposta libera e forzata.', category: 'blocco-6' },
      { id: 'L06', num: 'Guida 6', date: '6 Mag 2026', title: 'Risoluzione delle Equazioni alle Differenze', abstract: 'Versione discreta del Blocco 6: tabella dei modi con $a^t$, impulso $\\delta_0$ e radici complesse $\\rho e^{\\pm i\\omega}$, scorciatoia $Y_p = b^t/p(b)$, metodo classico via shift $\\Delta^k \\to t+k$, risonanza (incluso il caso speciale delle radici nulle), condizioni iniziali $Y(k) = y_k$, risposta libera e forzata.', category: 'blocco-7' },
    ],
  },
};

module.exports = { SITE, COURSES };
